
// refer threaddemo6 for code
// sleep() :: introduce delay to stagger execution 

class MyThread2 extends Thread {
    public void run() {
        for (int i = 0; i < 5; i++) {
            System.out.println(i + " : " + Thread.currentThread().getName());
        
            System.out.println(Thread.currentThread().getName()+"Sleeping........");
            try {
                Thread.sleep(10000);  // 
            } catch (InterruptedException e) {
                   e.printStackTrace();
            }
            
            System.out.println(Thread.currentThread().getName()+"Awaikin and work done ......");
        
        }
    }
}



public class ThreadDemo7{
    public static void main(String[] args) {
        System.out.println(Thread.currentThread().getName()+"started");
    
        MyThread2 t1 = new MyThread2();
        MyThread2 t2 = new MyThread2();
        MyThread2 t3 = new MyThread2();
        MyThread2 t4 = new MyThread2();

        t1.start();
        try { Thread.sleep(1000);} catch (InterruptedException e) {}
         
        t2.start();
        try { Thread.sleep(1000);} catch (InterruptedException e) {}

        t3.start();
        try { Thread.sleep(1000);} catch (InterruptedException e) {}
        
        t4.start();
        try { Thread.sleep(1000);} catch (InterruptedException e) {}

        
        System.out.println(Thread.currentThread().getName()+"finished"); 
    
    }
}




/*OUTPUT ::
 mainstarted
0 : Thread-0
Thread-0Sleeping........
0 : Thread-1
Thread-1Sleeping........
0 : Thread-2
Thread-2Sleeping........
0 : Thread-3
Thread-3Sleeping........
mainfinished
Thread-0Awaikin and work done ......
1 : Thread-0
Thread-0Sleeping........
Thread-1Awaikin and work done ......
1 : Thread-1
Thread-1Sleeping........
Thread-2Awaikin and work done ......
1 : Thread-2
Thread-2Sleeping........
Thread-3Awaikin and work done ......
1 : Thread-3
Thread-3Sleeping........
Thread-0Awaikin and work done ......
2 : Thread-0
Thread-0Sleeping........
Thread-1Awaikin and work done ......
2 : Thread-1
Thread-1Sleeping........
Thread-2Awaikin and work done ......
2 : Thread-2
Thread-2Sleeping........
Thread-3Awaikin and work done ......
2 : Thread-3
Thread-3Sleeping........
Thread-0Awaikin and work done ......
3 : Thread-0
Thread-0Sleeping........
Thread-1Awaikin and work done ......
3 : Thread-1
Thread-1Sleeping........
Thread-2Awaikin and work done ......
3 : Thread-2
Thread-2Sleeping........
Thread-3Awaikin and work done ......
3 : Thread-3
Thread-3Sleeping........
Thread-0Awaikin and work done ......
4 : Thread-0
Thread-0Sleeping........
Thread-1Awaikin and work done ......
4 : Thread-1
Thread-1Sleeping........
Thread-2Awaikin and work done ......
4 : Thread-2
Thread-2Sleeping........
Thread-3Awaikin and work done ......
4 : Thread-3
Thread-3Sleeping........
Thread-0Awaikin and work done ......
Thread-1Awaikin and work done ......
Thread-2Awaikin and work done ......
Thread-3Awaikin and work done ......
 */